// src/lib/data.ts

import type { Candidate, Job } from "@/types";
import { expBracket } from "@/lib/utils";

export const JOB: Job = {
  title: "Senior Frontend Engineer",
  department: "Engineering",
  location: "Remote · India",
  openPositions: 3,
  hiringManager: "Priya Sharma",
  totalApplicants: 47,
};

export const FUNNEL = [
  { stage: "Applied",     count: 47 },
  { stage: "Shortlisted", count: 18 },
  { stage: "Interview",   count: 9  },
  { stage: "Offered",     count: 3  },
  { stage: "Hired",       count: 1  },
];

const now = Date.now();
const days = (d: number) => new Date(now - d * 86_400_000).toISOString();
const hrs  = (h: number) => new Date(now - h * 3_600_000).toISOString();

export const CANDIDATES: Candidate[] = [

  /* ── APPLIED ──────────────────────────────────────── */
  {
    id: "c1",
    name: "Arjun Mehta",
    initials: "AM",
    avatarColor: "from-blue-500 to-indigo-600",
    email: "arjun.mehta@gmail.com",
    linkedIn: "linkedin.com/in/arjunmehta",
    currentRole: "Frontend Developer",
    currentCompany: "Razorpay",
    experience: 4,
    experienceBracket: expBracket(4),
    matchScore: 87,
    stage: "Applied",
    status: "Active",
    lastActivity: hrs(3),
    skills: [
      { label: "React",      color: "bg-blue-500/20 text-blue-300" },
      { label: "TypeScript", color: "bg-indigo-500/20 text-indigo-300" },
      { label: "Next.js",    color: "bg-slate-500/20 text-slate-300" },
      { label: "GraphQL",    color: "bg-pink-500/20 text-pink-300" },
    ],
    education: "B.Tech CSE — IIT Bombay, 2019",
    location: "Mumbai",
    summary:
      "4 years building high-performance React apps at Razorpay. Led CRA→Next.js migration cutting TTI by 40%.",
    timeline: [
      { id: "t1", stage: "Applied", date: hrs(3), actor: "Self", note: "Applied via LinkedIn" },
    ],
    notes: [
      { id: "n1", author: "Priya Sharma", authorInitials: "PS", content: "Strong portfolio. Schedule screening call.", createdAt: hrs(2) },
    ],
  },

  {
    id: "c2",
    name: "Sneha Kapoor",
    initials: "SK",
    avatarColor: "from-rose-500 to-pink-600",
    email: "sneha.kapoor@outlook.com",
    currentRole: "UI Engineer",
    currentCompany: "Swiggy",
    experience: 2,
    experienceBracket: expBracket(2),
    matchScore: 62,
    stage: "Applied",
    status: "Active",
    lastActivity: days(1),
    skills: [
      { label: "React",  color: "bg-blue-500/20 text-blue-300" },
      { label: "CSS",    color: "bg-cyan-500/20 text-cyan-300" },
      { label: "Figma",  color: "bg-violet-500/20 text-violet-300" },
    ],
    education: "B.E. CS — BITS Pilani, 2021",
    location: "Bangalore",
    summary: "2 years at Swiggy on consumer UI. Strong design eye and pixel-perfect implementation.",
    timeline: [
      { id: "t1", stage: "Applied", date: days(1), actor: "Self" },
    ],
    notes: [],
  },

  {
    id: "c3",
    name: "Rohan Das",
    initials: "RD",
    avatarColor: "from-amber-500 to-orange-600",
    email: "rohan.das@gmail.com",
    currentRole: "React Developer",
    currentCompany: "Freshworks",
    experience: 6,
    experienceBracket: expBracket(6),
    matchScore: 54,
    stage: "Applied",
    status: "Active",
    lastActivity: days(2),
    skills: [
      { label: "React", color: "bg-blue-500/20 text-blue-300" },
      { label: "Redux", color: "bg-purple-500/20 text-purple-300" },
      { label: "Jest",  color: "bg-green-500/20 text-green-300" },
    ],
    education: "MCA — VIT Vellore, 2017",
    location: "Chennai",
    summary: "6 years enterprise SaaS frontend. Solid Redux knowledge but portfolio lacks modern patterns.",
    timeline: [
      { id: "t1", stage: "Applied", date: days(2), actor: "Self" },
    ],
    notes: [
      { id: "n1", author: "Ravi Kumar", authorInitials: "RK", content: "Could fit if open to upskilling on modern stack.", createdAt: days(1) },
    ],
  },

  {
    id: "c14",
    name: "Ananya Gupta",
    initials: "AG",
    avatarColor: "from-indigo-500 to-blue-600",
    email: "ananya.g@gmail.com",
    currentRole: "Frontend Developer",
    currentCompany: "Dunzo",
    experience: 3,
    experienceBracket: expBracket(3),
    matchScore: 47,
    stage: "Applied",
    status: "Active",
    lastActivity: days(4),
    skills: [
      { label: "React",      color: "bg-blue-500/20 text-blue-300" },
      { label: "JavaScript", color: "bg-yellow-500/20 text-yellow-300" },
      { label: "HTML/CSS",   color: "bg-orange-500/20 text-orange-300" },
    ],
    education: "BCA — Symbiosis, 2020",
    location: "Pune",
    summary: "Junior-to-mid profile. No TypeScript or modern tooling experience yet.",
    timeline: [
      { id: "t1", stage: "Applied", date: days(4), actor: "Self" },
    ],
    notes: [],
  },

  /* ── SHORTLISTED ──────────────────────────────────── */
  {
    id: "c4",
    name: "Nisha Patel",
    initials: "NP",
    avatarColor: "from-violet-500 to-purple-600",
    email: "nisha.patel@yahoo.com",
    linkedIn: "linkedin.com/in/nishapatel",
    currentRole: "Senior Frontend Dev",
    currentCompany: "Zepto",
    experience: 5,
    experienceBracket: expBracket(5),
    matchScore: 91,
    stage: "Shortlisted",
    status: "Active",
    lastActivity: hrs(8),
    skills: [
      { label: "React",      color: "bg-blue-500/20 text-blue-300" },
      { label: "TypeScript", color: "bg-indigo-500/20 text-indigo-300" },
      { label: "Tailwind",   color: "bg-teal-500/20 text-teal-300" },
      { label: "Storybook",  color: "bg-pink-500/20 text-pink-300" },
      { label: "Vitest",     color: "bg-emerald-500/20 text-emerald-300" },
    ],
    education: "B.Tech IT — NIT Trichy, 2018",
    location: "Bangalore",
    summary: "Top performer at Zepto — owns the entire design system. Fast-track candidate.",
    timeline: [
      { id: "t1", stage: "Applied",     date: days(10), actor: "Self" },
      { id: "t2", stage: "Shortlisted", date: days(5),  actor: "Priya Sharma", note: "Moved after resume screening" },
    ],
    notes: [
      { id: "n1", author: "Priya Sharma", authorInitials: "PS", content: "Exceptional candidate. Fast-track to interview.", createdAt: days(5) },
    ],
  },

  {
    id: "c5",
    name: "Kiran Rao",
    initials: "KR",
    avatarColor: "from-teal-500 to-cyan-600",
    email: "kiran.rao@gmail.com",
    currentRole: "Frontend Engineer",
    currentCompany: "Meesho",
    experience: 3,
    experienceBracket: expBracket(3),
    matchScore: 75,
    stage: "Shortlisted",
    status: "Active",
    lastActivity: days(3),
    skills: [
      { label: "React",   color: "bg-blue-500/20 text-blue-300" },
      { label: "Vue.js",  color: "bg-green-500/20 text-green-300" },
      { label: "Node.js", color: "bg-lime-500/20 text-lime-300" },
    ],
    education: "B.E. ECE — Anna University, 2020",
    location: "Hyderabad",
    summary: "Versatile full-stack leaning frontend. Good React + Vue at Meesho's scale.",
    timeline: [
      { id: "t1", stage: "Applied",     date: days(12), actor: "Self" },
      { id: "t2", stage: "Shortlisted", date: days(6),  actor: "Ravi Kumar" },
    ],
    notes: [],
  },

  {
    id: "c15",
    name: "Sameer Khan",
    initials: "SK",
    avatarColor: "from-slate-500 to-zinc-600",
    email: "sameer.k@gmail.com",
    currentRole: "JavaScript Developer",
    currentCompany: "Byju's",
    experience: 12,
    experienceBracket: expBracket(12),
    matchScore: 58,
    stage: "Shortlisted",
    status: "On Hold",
    lastActivity: days(6),
    skills: [
      { label: "JavaScript", color: "bg-yellow-500/20 text-yellow-300" },
      { label: "Angular",    color: "bg-red-500/20 text-red-300" },
      { label: "jQuery",     color: "bg-blue-500/20 text-blue-300" },
    ],
    education: "B.Sc CS — Mumbai University, 2011",
    location: "Mumbai",
    summary: "12 years experience but primarily Angular/jQuery stack. React upskilling needed.",
    timeline: [
      { id: "t1", stage: "Applied",     date: days(16), actor: "Self" },
      { id: "t2", stage: "Shortlisted", date: days(8),  actor: "Ravi Kumar", note: "Shortlisted despite stack mismatch" },
    ],
    notes: [
      { id: "n1", author: "Ravi Kumar", authorInitials: "RK", content: "Check React proficiency in screening call.", createdAt: days(7) },
    ],
  },

  /* ── INTERVIEW ────────────────────────────────────── */
  {
    id: "c7",
    name: "Aditya Sharma",
    initials: "AS",
    avatarColor: "from-sky-500 to-blue-600",
    email: "aditya.s@gmail.com",
    linkedIn: "linkedin.com/in/adityasharma",
    currentRole: "Lead Frontend Engineer",
    currentCompany: "PhonePe",
    experience: 7,
    experienceBracket: expBracket(7),
    matchScore: 94,
    stage: "Interview",
    status: "Active",
    lastActivity: hrs(5),
    skills: [
      { label: "React",      color: "bg-blue-500/20 text-blue-300" },
      { label: "TypeScript", color: "bg-indigo-500/20 text-indigo-300" },
      { label: "Webpack",    color: "bg-blue-500/20 text-blue-300" },
      { label: "Web Perf",   color: "bg-orange-500/20 text-orange-300" },
      { label: "Micro FE",   color: "bg-cyan-500/20 text-cyan-300" },
    ],
    education: "B.Tech CSE — IIIT Hyderabad, 2016",
    location: "Bangalore",
    summary: "Led 5-person frontend team at PhonePe. Architected micro-frontend system for 100M+ users.",
    timeline: [
      { id: "t1", stage: "Applied",     date: days(20), actor: "Referral" },
      { id: "t2", stage: "Shortlisted", date: days(14), actor: "Priya Sharma" },
      { id: "t3", stage: "Interview",   date: days(7),  actor: "Priya Sharma", note: "Technical round 1 scheduled" },
    ],
    notes: [
      { id: "n1", author: "Priya Sharma", authorInitials: "PS", content: "Cleared round 1 with flying colors. Schedule system design round.", createdAt: days(3) },
    ],
  },

  {
    id: "c8",
    name: "Priyanka Singh",
    initials: "PS",
    avatarColor: "from-fuchsia-500 to-violet-600",
    email: "priyanka.singh@gmail.com",
    currentRole: "Frontend Engineer II",
    currentCompany: "Cred",
    experience: 5,
    experienceBracket: expBracket(5),
    matchScore: 82,
    stage: "Interview",
    status: "Active",
    lastActivity: days(1),
    skills: [
      { label: "React Native",   color: "bg-blue-500/20 text-blue-300" },
      { label: "React",          color: "bg-sky-500/20 text-sky-300" },
      { label: "TypeScript",     color: "bg-indigo-500/20 text-indigo-300" },
      { label: "TanStack Query", color: "bg-red-500/20 text-red-300" },
    ],
    education: "B.Tech CS — Delhi University, 2018",
    location: "Delhi",
    summary: "Strong React + RN at CRED. Passionate about mobile-first design patterns.",
    timeline: [
      { id: "t1", stage: "Applied",     date: days(18), actor: "Self" },
      { id: "t2", stage: "Shortlisted", date: days(11), actor: "Ravi Kumar" },
      { id: "t3", stage: "Interview",   date: days(4),  actor: "Priya Sharma" },
    ],
    notes: [],
  },

  {
    id: "c9",
    name: "Vikram Bose",
    initials: "VB",
    avatarColor: "from-orange-500 to-red-600",
    email: "vikram.b@gmail.com",
    currentRole: "SDE-II Frontend",
    currentCompany: "Flipkart",
    experience: 5,
    experienceBracket: expBracket(5),
    matchScore: 78,
    stage: "Interview",
    status: "Active",
    lastActivity: days(2),
    skills: [
      { label: "React",       color: "bg-blue-500/20 text-blue-300" },
      { label: "Redux",       color: "bg-purple-500/20 text-purple-300" },
      { label: "A/B Testing", color: "bg-yellow-500/20 text-yellow-300" },
      { label: "Perf Opt",    color: "bg-orange-500/20 text-orange-300" },
    ],
    education: "B.Tech — Jadavpur University, 2018",
    location: "Kolkata",
    summary: "5 years at Flipkart growth team. A/B testing and perf optimization at high traffic.",
    timeline: [
      { id: "t1", stage: "Applied",     date: days(22), actor: "Self" },
      { id: "t2", stage: "Shortlisted", date: days(13), actor: "Priya Sharma" },
      { id: "t3", stage: "Interview",   date: days(5),  actor: "Priya Sharma" },
    ],
    notes: [],
  },

  /* ── OFFERED ──────────────────────────────────────── */
  {
    id: "c10",
    name: "Meera Iyer",
    initials: "MI",
    avatarColor: "from-cyan-500 to-teal-600",
    email: "meera.iyer@gmail.com",
    linkedIn: "linkedin.com/in/meeraiyer",
    currentRole: "Staff Frontend Engineer",
    currentCompany: "Paytm",
    experience: 8,
    experienceBracket: expBracket(8),
    matchScore: 96,
    stage: "Offered",
    status: "Active",
    lastActivity: hrs(12),
    skills: [
      { label: "React",         color: "bg-blue-500/20 text-blue-300" },
      { label: "TypeScript",    color: "bg-indigo-500/20 text-indigo-300" },
      { label: "System Design", color: "bg-teal-500/20 text-teal-300" },
      { label: "Team Lead",     color: "bg-cyan-500/20 text-cyan-300" },
      { label: "Perf Eng",      color: "bg-green-500/20 text-green-300" },
    ],
    education: "M.Tech — IISc Bangalore, 2015",
    location: "Bangalore",
    summary: "Staff-level impact. Led frontend guild at Paytm (30 engineers). Offer extended — awaiting response.",
    timeline: [
      { id: "t1", stage: "Applied",     date: days(35), actor: "Referral" },
      { id: "t2", stage: "Shortlisted", date: days(28), actor: "Priya Sharma" },
      { id: "t3", stage: "Interview",   date: days(20), actor: "Priya Sharma", note: "4-round interview completed" },
      { id: "t4", stage: "Offered",     date: days(5),  actor: "Priya Sharma", note: "Offer sent: ₹38 LPA" },
    ],
    notes: [
      { id: "n1", author: "Priya Sharma", authorInitials: "PS", content: "Best candidate in the pipeline. Follow up Monday.", createdAt: days(4) },
    ],
  },

  {
    id: "c11",
    name: "Saurabh Joshi",
    initials: "SJ",
    avatarColor: "from-lime-500 to-green-600",
    email: "saurabh.j@gmail.com",
    currentRole: "Senior React Developer",
    currentCompany: "OYO",
    experience: 6,
    experienceBracket: expBracket(6),
    matchScore: 84,
    stage: "Offered",
    status: "Active",
    lastActivity: days(3),
    skills: [
      { label: "React",   color: "bg-blue-500/20 text-blue-300" },
      { label: "GraphQL", color: "bg-pink-500/20 text-pink-300" },
      { label: "Docker",  color: "bg-sky-500/20 text-sky-300" },
      { label: "CI/CD",   color: "bg-slate-500/20 text-slate-300" },
    ],
    education: "B.Tech — MNIT Jaipur, 2017",
    location: "Gurgaon",
    summary: "Full-stack frontend engineer. Offer extended — counter-offer expected.",
    timeline: [
      { id: "t1", stage: "Applied",     date: days(30), actor: "Self" },
      { id: "t2", stage: "Shortlisted", date: days(22), actor: "Ravi Kumar" },
      { id: "t3", stage: "Interview",   date: days(14), actor: "Priya Sharma" },
      { id: "t4", stage: "Offered",     date: days(6),  actor: "Priya Sharma" },
    ],
    notes: [],
  },

  {
    id: "c12",
    name: "Tanvi Desai",
    initials: "TD",
    avatarColor: "from-yellow-500 to-amber-600",
    email: "tanvi.d@gmail.com",
    currentRole: "Frontend Architect",
    currentCompany: "Udaan",
    experience: 9,
    experienceBracket: expBracket(9),
    matchScore: 88,
    stage: "Offered",
    status: "Active",
    lastActivity: days(1),
    skills: [
      { label: "React",        color: "bg-blue-500/20 text-blue-300" },
      { label: "Architecture", color: "bg-amber-500/20 text-amber-300" },
      { label: "Mentoring",    color: "bg-orange-500/20 text-orange-300" },
      { label: "TypeScript",   color: "bg-indigo-500/20 text-indigo-300" },
    ],
    education: "B.Tech CSE — IIIT Bangalore, 2014",
    location: "Bangalore",
    summary: "9 years frontend architecture at B2B SaaS scale. Ideal senior IC role.",
    timeline: [
      { id: "t1", stage: "Applied",     date: days(28), actor: "Self" },
      { id: "t2", stage: "Shortlisted", date: days(20), actor: "Priya Sharma" },
      { id: "t3", stage: "Interview",   date: days(12), actor: "Priya Sharma" },
      { id: "t4", stage: "Offered",     date: days(3),  actor: "Priya Sharma" },
    ],
    notes: [],
  },

  /* ── HIRED ────────────────────────────────────────── */
  {
    id: "c13",
    name: "Rahul Verma",
    initials: "RV",
    avatarColor: "from-emerald-500 to-teal-600",
    email: "rahul.v@gmail.com",
    linkedIn: "linkedin.com/in/rahulverma",
    currentRole: "Senior Frontend Engineer",
    currentCompany: "Groww",
    experience: 6,
    experienceBracket: expBracket(6),
    matchScore: 93,
    stage: "Hired",
    status: "Active",
    lastActivity: days(7),
    skills: [
      { label: "React",      color: "bg-blue-500/20 text-blue-300" },
      { label: "TypeScript", color: "bg-indigo-500/20 text-indigo-300" },
      { label: "Next.js",    color: "bg-slate-500/20 text-slate-300" },
      { label: "Playwright", color: "bg-emerald-500/20 text-emerald-300" },
      { label: "Tailwind",   color: "bg-teal-500/20 text-teal-300" },
    ],
    education: "B.Tech CSE — IIT Delhi, 2017",
    location: "Mumbai",
    summary: "Hired! Joins Feb 1. Led charts & portfolio team at Groww. Perfect culture fit.",
    timeline: [
      { id: "t1", stage: "Applied",     date: days(45), actor: "Referral" },
      { id: "t2", stage: "Shortlisted", date: days(38), actor: "Priya Sharma" },
      { id: "t3", stage: "Interview",   date: days(28), actor: "Priya Sharma", note: "3-round interview completed" },
      { id: "t4", stage: "Offered",     date: days(14), actor: "Priya Sharma", note: "Offer accepted: ₹36 LPA" },
      { id: "t5", stage: "Hired",       date: days(7),  actor: "Priya Sharma", note: "Joining date: Feb 1" },
    ],
    notes: [
      { id: "n1", author: "Priya Sharma", authorInitials: "PS", content: "Hire complete. Onboarding email sent.", createdAt: days(7) },
    ],
  },
];